version: "3.7"

services:
  traefik-university:
    container_name: traefik-university
    image: traefik
    command: --api.insecure=true --providers.docker #Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80" #The HTTP port
      - "8080:8080" #The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #so Traefik can listen to the Docker events

  postgresdb-university:
    container_name: postgresdb-university
    image: postgres:10
    command: [-cmax_prepared_transactions=100]
    ports:
      - "5432:5432"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    labels:
      - "traefik.ports=5432"
      - "traefik.frontend.rule=Host:postgresdb-university"
    environment:
      POSTGRES_PASSWORD: postgres

  pgadmin-university:
    container_name: pgadmin-university
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword
    volumes:
      - pgadmin-university-volume:/var/lib/pgadmin
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:pgadmin-university"
      - "traefik.http.routers.pgadmin-university.rule=Host(`pgadmin-university`)"

  university-beer-manager:
    container_name: university-beer-manager
    image: maven
    volumes:
      - "../beer-manager/:/app"
      # Mounting user's local .m2-directory,
      # for custom settings.xml and for caching dependencies.
      - "./.m2:/root/.m2"
    ports:
      - 5005:5005 # Debug port
      # - 8098:8098 # Backend HTTP server port
    working_dir: /app
    command: "mvn quarkus:dev -Dquarkus.http.host=0.0.0.0"

  university-beer-manager-ui:
    container_name: university-beer-manager-ui
    build: ../beer-manager-ui
    ports:
      - "4200:4200"
    volumes:
      - "/app/node_modules"
      - "../beer-manager-ui:/app"

volumes:
  pgadmin-university-volume:
